### ISSUE TITLE
Problem with iOS 

### ISSUE THREAD

**Issue by Alireza1044** [EbrahimTahernejad/Tun2SocksKit#14]
Hi,

Thanks for the wrapper.

I'm trying to use this to forward iPhone's traffic to xray-core using NetworkExtension, however it seems the connection between tun2socks and xray is broken. Could you help me please? 

Network settings:
```
let settings = NEPacketTunnelNetworkSettings(tunnelRemoteAddress: "254.1.1.1")
settings.mtu = 8500
let ipv4Settings = NEIPv4Settings(addresses: ["198.18.0.1"], subnetMasks: ["255.255.0.0"])
ipv4Settings.includedRoutes = [NEIPv4Route.default()]
settings.ipv4Settings = ipv4Settings
let dns = NEDNSSettings(servers: ["1.1.1.1", "8.8.8.8"])
settings.dnsSettings = dns
settings.proxySettings = nil
```

tun2socks config:
```
tunnel:
  mtu: 8500

socks5:
  port: 1081
  address: ::1
  udp: 'udp'

misc:
  task-stack-size: 20480
  connect-timeout: 5000
  read-write-timeout: 60000
  log-file: \(logFile.path(percentEncoded: false))
  log-level: debug
  limit-nofile: 65535
```

xray intbounds config:
```
"inbounds" : [
    {
      "port" : 1081,
      "protocol" : "socks",
      "settings" : {
        "auth" : "noauth",
        "udp" : true
      },
      "sniffing" : {
        "destOverride" : [
          "http",
          "tls",
          "quic",
          "fakedns"
        ],
        "enabled" : true,
        "routeOnly" : true
      },
      "tag" : "socks"
    }
  ],
```

Do you have any idea of where the problem is?
