### ISSUE TITLE
RESOURCE_TYPE_MEMORY

### ISSUE THREAD

**Issue by dhp5** [EbrahimTahernejad/Tun2SocksKit#26]
This code reports an error.
``
hev_socks5_tunnel_main_from_str(content.cString(using: .utf8), UInt32(content.count), fileDescriptor)
``
````
Thread 3: EXC_RESOURCE (RESOURCE_TYPE_MEMORY: high watermark memory limit exceeded) (limit=50 MB)
The operating system stopped the process because the process exceeded a limit on resource consumption, like CPU time or memory.
````
version:v4.7.5

My Configuration：
````
  let socks5Config = """
        tunnel:
            mtu: 1500
        
        socks5:
            port: 10808
            address: 127.0.0.1
            udp: 'udp'
        
        misc:
            task-stack-size: 20480
            connect-timeout: 5000
            read-write-timeout: 60000
            log-file: stderr
            log-level: debug
            limit-nofile: 65535
                    
        """
````
