### ISSUE TITLE
Boot mode string failed. result is -1

### ISSUE THREAD

**Issue by CreatSuns** [EbrahimTahernejad/Tun2SocksKit#8]
version:3.6.7

This is started in string mode， result is fail

```
let config = """
            tunnel:
              mtu: 9000
            socks5:
              port: \(port)
              address: ::1
              udp: 'udp'
            misc:
              task-stack-size: 20480
              connect-timeout: 5000
              read-write-timeout: 60000
              log-file: stderr
              log-level: error
              limit-nofile: 65535
            """
Socks5Tunnel.run(withConfig: .string(content: config)) { code in
            NSLog("HEV_SOCKS5_TUNNEL_MAIN: \(code)")
}

```
        
but When I started with.file(), it was successful
